apiVersion: apps/v1
kind: Deployment
metadata:
  name: p2-deployment
  labels:
    tier: frontend
    app: p2
spec:
  selector:
    matchLabels:
      app: p2
  replicas : 6
  template:
    metadata:
      labels:
        app: p2
    spec:
      containers:
      - name: project2-container
        image: cpowell99/project2:project2