apiVersion: v1
kind: Namespace
metadata:
  name: project2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: p2-deployment
#  namespace: project2
  labels:
    tier: frontend
    app: p2
spec:
  selector:
    matchLabels:
      app: p2
  replicas : 2
  template:
    metadata:
      labels:
        app: p2
    spec:
      containers:
      - name: project2-container
        image: cpowell99/project2:project2

---
apiVersion: v1
kind: Service
metadata:
  name: p2
#  namespace: project2
spec:
  type: NodePort
  ports:
  - port: 8088
    targetPort: 8088
    nodePort: 30003
  selector:
    app: p2